version: '3.1'

services:

    base-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: ubuntu:20.04
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest


    nrp-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-ubuntu20-env:latest
        depends_on:
        - base-env


    nest-env:
        build:
            context: .
            dockerfile: dockerfiles/nest.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nest-ubuntu20-env:latest
        depends_on:
        - base-env


    gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-ubuntu20-env:latest
        depends_on:
        - base-env


    gazebo-nest-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/nest-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-nest-ubuntu20-env:latest
        depends_on:
        - nest-env


    nrp-gazebo-nest-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-nest-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-gazebo-nest-ubuntu20-env:latest
        depends_on:
        - gazebo-nest-env


    tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/tvb.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/tvb-ubuntu20-env:latest
        depends_on:
        - base-env


    opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/opensim.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-ubuntu20-env:latest
        depends_on:
        - base-env


    opensim-tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/tvb.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-tvb-ubuntu20-env:latest
        depends_on:
        - opensim-env


    nrp-opensim-tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-tvb-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-opensim-tvb-ubuntu20-env:latest
        depends_on:
        - opensim-tvb-env
