version: '3.1'

services:

    base-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: ubuntu:20.04
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest


    nrp-vanilla:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
                CMAKE_CACHE_FILE: .ci/cmake_cache/vanilla.cmake
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-vanilla-ubuntu20:latest
        depends_on:
        - base-env


    nest-env:
        build:
            context: .
            dockerfile: dockerfiles/nest.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nest-ubuntu20-env:latest
        depends_on:
        - base-env


    gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-ubuntu20-env:latest
        depends_on:
        - base-env


    gazebo-nest-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/nest-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-nest-ubuntu20-env:latest
        depends_on:
        - nest-env


    nrp-gazebo-nest:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/gazebo-nest-ubuntu20-env:latest
                CMAKE_CACHE_FILE: .ci/cmake_cache/nest-gazebo.cmake
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-gazebo-nest-ubuntu20:latest
        depends_on:
        - gazebo-nest-env


    tvb-env:
        build:
            context: .
            dockerfile: dockerfiles/tvb.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/tvb-ubuntu20-env:latest
        depends_on:
        - base-env


    opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/opensim.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-ubuntu20-env:latest
        depends_on:
        - base-env


    nrp-opensim:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/opensim-ubuntu20-env:latest
                CMAKE_CACHE_FILE: .ci/cmake_cache/opensim.cmake
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-opensim-ubuntu20-env:latest
        depends_on:
        - opensim-env


    nrp-tvb:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/tvb-ubuntu20-env:latest
                CMAKE_CACHE_FILE: .ci/cmake_cache/tvb.cmake
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-tvb-ubuntu20-env:latest
        depends_on:
        - tvb-env


    base-nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: nvidia/cudagl:11.4.2-base-ubuntu20.04
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-nvidia-cuda-ubuntu20-env:latest


    nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/nvidia_cuda.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/base-nvidia-cuda-ubuntu20-env:latest
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nvidia-cuda-ubuntu20-env:latest
        depends_on:
        - base-nvidia-cuda-env


    nrp-nvidia-cuda:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: nexus.neurorobotics.ebrains.eu:443/nrp-core/nvidia-cuda-ubuntu20-env:latest
                CMAKE_CACHE_FILE: .ci/cmake_cache/nrp-nvidia-cuda.cmake
        image: nexus.neurorobotics.ebrains.eu:443/nrp-core/nrp-nvidia-cuda-ubuntu20:latest
        depends_on:
        - nvidia-cuda-env
